name: Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-shell:
    name: Shell Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y shellcheck shfmt

      - name: Run shell linting
        run: |
          make check-lint
